name: test_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconly: ^1.0.1
  google_maps_flutter: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  widget_and_text_animator: ^1.1.5
  geolocator: ^12.0.0
  location: ^6.0.2
  flutter_map: ^7.0.2
  dropdown_button2: ^2.3.9



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/